### ISSUE TITLE
CANT INSTALL LOCALLY 

### ISSUE THREAD

**Issue by TalibY22** [InvoiceShelf/InvoiceShelf#257] opened 2024-12-21 17:50 UTC
### Issue filing pre-requisites

- [X] I've checked the documentation.
- [X] I've looked for similar issues both Open and Closed.
- [X] Ive tried clearing both cache and cookies in my browser or tried opening the app in the Incognito/InPrivate window.

### Describe the bug

When installing the app locally it says error occured "plc check if ur server are online and try again" this  happens after setting up the database note i followed the documentattion did use yarn run build but the issue still persists any help regarding this issue will be highly appreciated 

### Steps to Reproduce the issue

Do the installation

### Expected behavior

Installation should happend without any issue 

### Actual behavior

Install not happening 

### InvoiceShelf version

latest

### PHP version

8.2

### Database type

ALL

### Database version

latest

### Web Browser

Chrome

### Server OS

linux parrot os

**Comment by TalibY22** [comment] 2024-12-21 17:50
PLZ DONT CLOSE THIS ISSUE I NEED HELP WITH THIS

**Comment by TalibY22** [comment] 2024-12-21 17:55
When i say locally i mean on my computer which is running linux debian tried all that was suggested previously nothing works any help regardding this issue will be appreciated anyone else who faced this issue before?

**Comment by rihards-simanovics** [comment] 2024-12-21 18:10
Hi @TalibY22, I closed issue #255 because we treat GitHub issues as __bug reports__ and __feature requests__ for the software — not support tickets. Additionally, each comment you or anyone else makes in the GitHub issue generates email notifications, which can distract from real issues as those, at least for me, take higher priority.

You are asking a question about installation, which falls outside what we can do in GitHub. For support, I invite you to join our [Discord server](https://discord.gg/hwg2FtwWHW); mention that you are the person who opened issue #255, and I or someone else will try to help you.

Closing as duplicate of #255.

**Closed by rihards-simanovics** 2024-12-21 18:10 UTC
Labels: bug, triage
