### ISSUE TITLE
Error 500 wwhen a customer wants to see their invoice

### ISSUE THREAD

**Issue by OniriCorpe** [InvoiceShelf/InvoiceShelf#233] opened 2024-11-29 23:01 UTC
### Issue filing pre-requisites

- [X] I've checked the documentation.
- [X] I've looked for similar issues both Open and Closed.
- [X] Ive tried clearing both cache and cookies in my browser or tried opening the app in the Incognito/InPrivate window.

### Describe the bug

When I click on the invoice link in the sended email to access it, I get a 500 error

### Steps to Reproduce the issue

1. Send an invoice to your own email address
2. Open the invoice's mail
3. Click the link to open the invoice PDF
4. See the error

### Expected behavior

The invoice is showed instead of the error

### Actual behavior

the "500 Server Error" is showed instead of the invoice's PDF

### InvoiceShelf version

2.0

### PHP version

8.2

### Database type

PostgreSQL

### Database version

psql (PostgreSQL) 13.18 (Debian 13.18-0+deb11u1)

### Web Browser

Firefox 133 / iOS Safari 18.1.1

### Server OS

YunoHost / Debian 11

### Reverse-proxy logs

```irc logs
2a01:e0a:1ef::aaaa - - [29/Nov/2024:23:54:57 +0100] "GET /customer/invoices/view/1ZwgJYl3e376PmV0DO25 HTTP/2.0" 500 6609 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0"

2a01:cb01:853::bbbb - - [30/Nov/2024:00:00:51 +0100] "GET /customer/invoices/view/1ZwgJYl3e376PmV0DO25 HTTP/2.0" 500 6609 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 18_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Mobile/15E148 Safari/604.1"
```

### Laravel/PHP logs

```irc logs
[2024-11-29 22:54:57] production.ERROR: Carbon\Carbon::rawAddUnit(): Argument #3 ($value) must be of type int|float, string given, called in /var/www/invoiceshelf/vendor/nesbot/carbon/src/Carbon/Traits/Units.php on line 356 {"userId":1,"exception":"[object] (TypeError(code: 0): Carbon\\Carbon::rawAddUnit(): Argument #3 ($value) must be of type int|float, string given, called in /var/www/invoiceshelf/vendor/nesbot/carbon/src/Carbon/Traits/Units.php on line 356 at /var/www/invoiceshelf/vendor/nesbot/carbon/src/Carbon/Traits/Units.php:455)
[stacktrace]
#0 /var/www/invoiceshelf/vendor/nesbot/carbon/src/Carbon/Traits/Units.php(356): Carbon\\Carbon::rawAddUnit()
#1 /var/www/invoiceshelf/vendor/nesbot/carbon/src/Carbon/Traits/Date.php(2925): Carbon\\Carbon->addUnit()
#2 /var/www/invoiceshelf/vendor/nesbot/carbon/src/Carbon/Traits/Date.php(2616): Carbon\\Carbon->callModifierMethod()
#3 /var/www/invoiceshelf/app/Models/EmailLog.php(26): Carbon\\Carbon->__call()
#4 /var/www/invoiceshelf/app/Http/Controllers/V1/Customer/InvoicePdfController.php(20): App\\Models\\EmailLog->isExpired()
#5 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\V1\\Customer\\InvoicePdfController->getPdf()
#6 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#7 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#8 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Routing/Route.php(206): Illuminate\\Routing\\Route->runController()
#9 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\Routing\\Route->run()
#10 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#11 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#13 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#15 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#17 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#19 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#21 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#22 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#24 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#26 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#28 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#29 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#30 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#31 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#32 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#33 /var/www/invoiceshelf/app/Http/Middleware/ConfigMiddleware.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\ConfigMiddleware->handle()
#35 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#37 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#38 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#40 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#42 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#43 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#45 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#46 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
#48 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#50 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#52 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#54 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#56 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#57 /var/www/invoiceshelf/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1176): Illuminate\\Foundation\\Http\\Kernel->handle()
#58 /var/www/invoiceshelf/public/index.php(17): Illuminate\\Foundation\\Application->handleRequest()
#59 {main}
"}
```

**Comment by rihards-simanovics** [comment] 2024-11-30 02:04
@OniriCorpe are you able to view invoices preview or is it only for the invoices that are sent to a customer via email?

**Comment by OniriCorpe** [comment] 2024-11-30 03:01
I can see the invoices previews or open a PDF link like this one `/invoices/pdf/jL532GVA6Lzeb4mz8O17` but not when i'm acting like a customer with their dedicated links `/customer/invoices/view/1ZwgJYl3e376PmV0DO25`

**Comment by rihards-simanovics** [comment] 2024-11-30 03:38
Duplicate of #173

Ok so then it's not a PDF generation bug. Hey @gdarko, I think it's worth us making a minor release with the patches and fixes we have until now.

**Closed by rihards-simanovics** 2024-11-30 03:38 UTC
Labels: bug, needs testing, needs investigation, code quality
