### ISSUE TITLE
Custom fields in the PDF template return error

### ISSUE THREAD

**Issue by NightlandDriver** [InvoiceShelf/InvoiceShelf#50] opened 2024-03-22 13:37 UTC
**Describe the bug**
Custom fields in the PDF template return error: Attempt to read property on null.
Migrated from Crater and there it was working without Problems.

**Expected behavior**
Custom fields in the PDF template should display the correct value of the field.

**Screenshots**
Screenshot 1: View Invoice PDF
![screenshot_01](https://github.com/InvoiceShelf/InvoiceShelf/assets/69898403/932eca70-d641-4eb3-b180-f3e799be811b)

Screenshot 2: Custom Fields Settings
![screenshot_02](https://github.com/InvoiceShelf/InvoiceShelf/assets/69898403/bda6270c-285a-405c-b804-35a097660e4c)

**Please complete the following information:**
- InvoiceShelf version: 1.1.0
- PHP version: 8.2
- Database type and version: MySQL

**Comment by Timo972** [comment] 2024-04-16 15:13
Hey @NightlandDriver,
I just tried to reproduce your issue on master branch and it seems to be working fine.
Maybe it is related to your migration from Crater to InvoiceShelf.

**Comment by Timo972** [comment] 2024-04-16 15:25
In fact if you migrated from Crater to InvoiceShelf it might be a similar issue to #44 which is being resolved by #58

**Comment by azaricstefan** [comment] 2024-05-22 22:49
@NightlandDriver try with my PR if it fixes your issue.

**Closed** 2024-05-23 14:37 UTC
Labels: bug

**Comment by azaricstefan** [comment] 2024-05-23 14:59
Glad it got fixed 😀

**Comment by rihards-simanovics** [comment] 2024-12-11 22:40
linked to https://github.com/InvoiceShelf/InvoiceShelf/issues/252
