### ISSUE TITLE
Logo not displayed in pdf

### ISSUE THREAD

**Issue by Hoschi1982** [InvoiceShelf/InvoiceShelf#113] opened 2024-07-06 20:58 UTC
**Describe the bug**
When i create a new estimate oder invoice pdf the uploaded logo for the company is not displayed.
Instead to display the logo the following text is displayed: "Company Logo Image not found or type unknown"

**Expected behavior**
The logo should be displayed.

**docker image**
invoiceshelf/invoiceshelf:1.2.2

Can someone reproduce it?

**Comment by r3xx0n** [comment] 2024-07-07 17:33
Same Problem, just installed InvoiceShelf.

Logo PNG with transparent Background, even converted it to base64. Not working.

**Comment by StuSerious** [comment] 2024-07-09 09:07
can confirm I'm having the same issue on 1.2.2

![image](https://github.com/InvoiceShelf/InvoiceShelf/assets/53015230/d6dac852-b117-47af-8d8b-b60551448650)

**Comment by gdarko** [comment] 2024-07-09 12:35
Hey @Hoschi1982 , @r3xx0n , @StuSerious 

Can you provide more details about  the environment, how did you set up InvoiceShelf? 

Thanks.

**Comment by StuSerious** [comment] 2024-07-09 12:46
Sorry, on second thought, my comment was a bit useless. Here are some more info:

I have the docker container running in a Proxmox CT running Ubuntu 23.10 mantic.
If you run PVE, I can provide a snapshot of my instance so you have 1:1 replication.

InvoiceShelf version is latest (1.2.2).

The error in the PDF is "Image not found or type unknown"

I'm not really sure where to look for logs, but willing to dig around if you can tip me in the right direction.

Let me know what you need, and thank you for your time. This is an amazing piece of software!

**Comment by mchev** [comment] 2024-07-09 12:58
Duplicate of #62

**Comment by gdarko** [comment] 2024-07-09 14:28
Closing this in favor of https://github.com/InvoiceShelf/docker/issues/15

**Closed by gdarko** 2024-07-09 14:28 UTC
